#!/bin/bash
set -euo pipefail

# Helm Deployment Helper Script
# This script helps deploy Obot with custom CA images to Kubernetes

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAMESPACE="${NAMESPACE:-obot-system}"
RELEASE_NAME="${RELEASE_NAME:-obot}"
REGISTRY="${REGISTRY:-your-registry.example.com}"
OBOT_REPO="${OBOT_REPO:-obot}"
MCP_REPO="${MCP_REPO:-obot}"
OBOT_TAG="${OBOT_TAG:-enterprise}"
MCP_TAG="${MCP_TAG:-latest}"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

usage() {
    cat << EOF
Usage: $0 [OPTIONS] COMMAND

Deploy Obot with custom CA images to Kubernetes.

COMMANDS:
    install             Install Obot using Helm
    upgrade             Upgrade existing Obot installation
    generate-values     Generate values.yaml with custom images
    verify              Verify deployment

OPTIONS:
    -n, --namespace NS      Kubernetes namespace (default: obot-system)
    -r, --release NAME      Helm release name (default: obot)
    --registry URL          Container registry URL
    --obot-repo NAME        Obot repository name (default: obot)
    --mcp-repo NAME         MCP repository name (default: obot)
    --obot-tag TAG          Obot image tag (default: enterprise)
    --mcp-tag TAG           MCP images tag (default: latest)
    -f, --values FILE       Additional Helm values file
    -h, --help              Show this help message

EXAMPLES:
    # Generate values.yaml
    $0 generate-values

    # Install Obot
    $0 install

    # Upgrade with custom values
    $0 -f custom-values.yaml upgrade

EOF
}

check_prerequisites() {
    log_info "Checking prerequisites..."
    
    if ! command -v kubectl &> /dev/null; then
        log_error "kubectl is not installed"
        exit 1
    fi
    
    if ! command -v helm &> /dev/null; then
        log_error "Helm is not installed"
        exit 1
    fi
    
    log_info "Prerequisites check passed"
}

generate_values() {
    local values_file="${1:-$SCRIPT_DIR/values-custom.yaml}"
    
    log_info "Generating Helm values file: $values_file"
    
    cat > "$values_file" << EOF
# Custom Obot Helm Values with Enterprise CA
# Generated by deploy.sh

# Use custom Obot image with enterprise CA
image:
  repository: $REGISTRY/$OBOT_REPO
  tag: $OBOT_TAG
  pullPolicy: IfNotPresent

# Configure MCP server images with enterprise CA
config:
  OBOT_SERVER_MCPBASE_IMAGE: "$REGISTRY/$MCP_REPO/mcp-base:$MCP_TAG"
  OBOT_SERVER_MCPREMOTE_SHIM_BASE_IMAGE: "$REGISTRY/$MCP_REPO/nanobot-shim:$MCP_TAG"
  OBOT_SERVER_MCPHTTPWEBHOOK_BASE_IMAGE: "$REGISTRY/$MCP_REPO/webhook-converter:$MCP_TAG"
  OBOT_SERVER_MCPRUNTIME_BACKEND: "docker"

# Configure image pull secrets if using private registry
# Uncomment and configure if needed:
# imagePullSecrets:
#   - name: registry-credentials

# mcpImagePullSecrets:
#   - name: mcp-registry-secret
#     registry: $REGISTRY
#     username: your-username
#     password: your-password
#     email: your-email@example.com

# Additional Obot configuration
# config:
#   OBOT_SERVER_ENABLE_AUTHENTICATION: "true"
#   OPENAI_API_KEY: "your-api-key"

EOF
    
    log_info "Values file generated: $values_file"
    log_info "Please review and customize the values file before deployment"
}

install_obot() {
    local values_file="${ADDITIONAL_VALUES:-$SCRIPT_DIR/values-custom.yaml}"
    
    log_info "Installing Obot to namespace: $NAMESPACE"
    
    # Create namespace if it doesn't exist
    if ! kubectl get namespace "$NAMESPACE" &> /dev/null; then
        log_info "Creating namespace: $NAMESPACE"
        kubectl create namespace "$NAMESPACE"
    fi
    
    # Check if values file exists
    if [ ! -f "$values_file" ]; then
        log_warn "Values file not found: $values_file"
        log_info "Generating default values file..."
        generate_values "$values_file"
    fi
    
    # Add Obot Helm repository
    log_info "Adding Obot Helm repository..."
    helm repo add obot https://obot-platform.github.io/obot || true
    helm repo update
    
    # Install Obot
    log_info "Installing Obot with Helm..."
    helm install "$RELEASE_NAME" obot/obot \
        --namespace "$NAMESPACE" \
        --create-namespace \
        -f "$values_file"
    
    log_info "Obot installed successfully"
    log_info "Run '$0 verify' to check deployment status"
}

upgrade_obot() {
    local values_file="${ADDITIONAL_VALUES:-$SCRIPT_DIR/values-custom.yaml}"
    
    log_info "Upgrading Obot in namespace: $NAMESPACE"
    
    if [ ! -f "$values_file" ]; then
        log_error "Values file not found: $values_file"
        log_info "Run '$0 generate-values' first"
        exit 1
    fi
    
    helm upgrade "$RELEASE_NAME" obot/obot \
        --namespace "$NAMESPACE" \
        -f "$values_file"
    
    log_info "Obot upgraded successfully"
}

verify_deployment() {
    log_info "Verifying Obot deployment..."
    echo
    
    log_info "Checking pods..."
    kubectl get pods -n "$NAMESPACE" -l app.kubernetes.io/name=obot
    echo
    
    log_info "Checking services..."
    kubectl get svc -n "$NAMESPACE" -l app.kubernetes.io/name=obot
    echo
    
    log_info "Checking Obot logs (last 20 lines)..."
    kubectl logs -n "$NAMESPACE" -l app.kubernetes.io/name=obot --tail=20 || true
    echo
    
    # Check if Obot is using custom image
    local image=$(kubectl get deployment -n "$NAMESPACE" "$RELEASE_NAME" -o jsonpath='{.spec.template.spec.containers[0].image}')
    log_info "Obot image: $image"
    
    if [[ "$image" == *"$REGISTRY"* ]]; then
        log_info "✓ Using custom registry image"
    else
        log_warn "⚠ Not using custom registry image"
    fi
    echo
    
    # Test CA certificate
    log_info "Testing CA certificate in Obot pod..."
    local pod=$(kubectl get pod -n "$NAMESPACE" -l app.kubernetes.io/name=obot -o jsonpath='{.items[0].metadata.name}')
    if [ -n "$pod" ]; then
        kubectl exec -n "$NAMESPACE" "$pod" -- ls -l /etc/ssl/certs/ca-certificates.crt || true
    fi
}

# Parse arguments
COMMAND=""
ADDITIONAL_VALUES=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        -r|--release)
            RELEASE_NAME="$2"
            shift 2
            ;;
        --registry)
            REGISTRY="$2"
            shift 2
            ;;
        --obot-repo)
            OBOT_REPO="$2"
            shift 2
            ;;
        --mcp-repo)
            MCP_REPO="$2"
            shift 2
            ;;
        --obot-tag)
            OBOT_TAG="$2"
            shift 2
            ;;
        --mcp-tag)
            MCP_TAG="$2"
            shift 2
            ;;
        -f|--values)
            ADDITIONAL_VALUES="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        install|upgrade|generate-values|verify)
            COMMAND="$1"
            shift
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Main execution
main() {
    if [ -z "$COMMAND" ]; then
        log_error "No command specified"
        usage
        exit 1
    fi
    
    check_prerequisites
    
    case $COMMAND in
        install)
            install_obot
            ;;
        upgrade)
            upgrade_obot
            ;;
        generate-values)
            generate_values
            ;;
        verify)
            verify_deployment
            ;;
        *)
            log_error "Unknown command: $COMMAND"
            usage
            exit 1
            ;;
    esac
}

main
