name: Test Docker Build
on:
  workflow_dispatch:
    inputs:
      base_image:
        description: Base builder image to use. Empty uses ghcr.io/<repo>/base:latest.
        required: false
      runtime_base_image:
        description: Runtime base image to use. Empty uses ghcr.io/<repo owner>/obot-runtime-base:latest. Use runtime-base to build it from this Dockerfile.
        required: false

env:
  BASE_IMAGE: ghcr.io/${{ github.repository }}/base:latest
  RUNTIME_BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/obot-runtime-base:latest

jobs:
  build:
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Depot
        uses: depot/setup-action@v1

      - name: Build Docker Image
        uses: depot/build-push-action@v1
        with:
          project: bbqjs4tj1g
          context: .
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=${{ inputs.base_image || env.BASE_IMAGE }}
            RUNTIME_BASE_IMAGE=${{ inputs.runtime_base_image || env.RUNTIME_BASE_IMAGE }}
